{% set version = "1.4.15" %}

package:
  name: kealib
  version: {{ version }}

source:
  url: https://github.com/ubarsc/kealib/releases/download/kealib-{{ version }}/kealib-{{ version }}.tar.gz
  sha256: 40f2573c00f005f93c1fa88f1f13bfbd485cbc7a9b3f1c706931e69bff17dae4

build:
  number: 0
  skip: true  # [win and vc<14]
  run_exports:
    - {{ pin_subpackage('kealib', max_pin='x.x') }}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
    - make  # [unix]
  host:
    - hdf5
  run:
    - hdf5

#test:
#  requires:
#    - libgdal
#  commands:
#    # check we haven't broken GDAL
#    - gdal_translate --formats

about:
  home: http://kealib.org/
  license: MIT
  license_file: LICENSE.txt
  summary: The KEA format provides an implementation of the GDAL specification within the the HDF5 file format.
  description: |
    "KEA is an image file format, named after the New Zealand bird, that provides a full implementation 
    of the GDAL data model and is implemented within a HDF5 file. A software library, libkea, is used 
    to access the file format. The format has comparable performance with existing formats while 
    producing smaller file sizes and is already within active use for a number of projects 
    within Landcare Research, New Zealand, and the wider community."
  doc_url: https://gdal.org/drivers/raster/kea.html
  dev_url: https://github.com/ubarsc/kealib

extra:
  recipe-maintainers:
    - gillins
    - danclewley
