{% set version = "1.6.0" %}

package:
  name: kealib-split
  version: {{ version }}

source:
  url: https://github.com/ubarsc/kealib/releases/download/kealib-{{ version }}/kealib-{{ version }}.tar.gz
  sha256: c05a8621d86e293de0f45fc194751f67f841a68e7a45d95b2f37fcdfb2dc2c14

build:
  number: 1
  skip: true  # [win and vc<14]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('cxx') }}
    - cmake
    - make  # [unix]
  host:
    - hdf5
  run:
    - hdf5

outputs:
  - name: kealib
    script: install_lib.sh  # [unix]
    script: install_lib.bat  # [win]
    build:
      run_exports:
        - {{ pin_subpackage('kealib', max_pin='x.x') }}
    requirements:
      build:
        - {{ compiler('c') }}
        - {{ stdlib("c") }}
        - {{ compiler('cxx') }}
        - cmake
        - make  # [unix]
      host:
        - hdf5
      run:
        - hdf5

  - name: pykealib
    script: build_python.sh  # [unix]
    script: bld_python.bat  # [win]
    entry_points:
      - kea_build_neighbours = kealib.build_neighbours:main
    requirements:
      build:
        - {{ compiler('c') }}
        - {{ stdlib("c") }}
        - {{ compiler('cxx') }}
        - cmake
        - make  # [unix]
        # don't install cross compile etc as this breaks the cmake/python stuff on Linux
        # but appears to be needed on OSX
        - python                                 # [osx and build_platform != target_platform]
        - cross-python_{{ target_platform }}     # [osx and build_platform != target_platform]
      host:
        - python
        - numpy
        - pybind11
        # ensure we get a recent awkward... By default an extremely old one can be selected.
        - awkward >=2
        - {{ pin_subpackage('kealib', exact=True) }}
      run:
        - python
        # ensure we get a recent awkward... By default an extremely old one can be selected.
        - awkward >=2
        - {{ pin_subpackage('kealib', exact=True) }}
    # skip for now - neither GDAL nor fakegdal installed at this point
    # Adding dependency on GDAL ends up being circular.
    # Maybe should install fakegdal ?
    #test:
    #  imports:
    #    - kealib.extrat
    #  commands:
    #    - kea_build_neighbours -h

#test:
#  requires:
#    - libgdal
#  commands:
#    # check we haven't broken GDAL
#    - gdal_translate --formats

about:
  home: http://kealib.org/
  license: MIT
  license_file: LICENSE.txt
  summary: The KEA format provides an implementation of the GDAL specification within the the HDF5 file format.
  description: |
    "KEA is an image file format, named after the New Zealand bird, that provides a full implementation 
    of the GDAL data model and is implemented within a HDF5 file. A software library, libkea, is used 
    to access the file format. The format has comparable performance with existing formats while 
    producing smaller file sizes and is already within active use for a number of projects 
    within Landcare Research, New Zealand, and the wider community."
  doc_url: https://gdal.org/drivers/raster/kea.html
  dev_url: https://github.com/ubarsc/kealib

extra:
  recipe-maintainers:
    - gillins
    - danclewley
